/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-siyoung74.git ./01-hello-world-siyoung74.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-ksheard.git ./01-hello-world-ksheard.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-dakotajacobs.git ./01-hello-world-dakotajacobs.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-blu21.git ./01-hello-world-blu21.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-gmahesh44.git ./02-gc-percent-gmahesh44.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-saadtassaduq786.git ./01-hello-world-saadtassaduq786.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-mwuser.git ./01-hello-world-mwuser.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-watkinsta.git ./01-hello-world-watkinsta.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-jhm471.git ./01-hello-world-jhm471.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-tejpalgill.git ./01-hello-world-tejpalgill.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-ReichardKyle.git ./01-hello-world-ReichardKyle.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-pickles0618.git ./01-hello-world-pickles0618.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-R-Mayers.git ./01-hello-world-R-Mayers.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-shoos001.git ./01-hello-world-shoos001.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-aditithakkar17.git ./01-hello-world-aditithakkar17.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-drewhonson.git ./01-hello-world-drewhonson.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-shlosman.git ./01-hello-world-shlosman.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-ccole1993.git ./01-hello-world-ccole1993.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-greenkidneybean.git ./01-hello-world-greenkidneybean.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-drewhonson.git ./02-gc-percent-drewhonson.git
/usr/bin/git submodule add https://github.com/faes-biof/08-make-a-plot-jhm471.git ./08-make-a-plot-jhm471.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-ksheard.git ./02-gc-percent-ksheard.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-chelseabender.git ./01-hello-world-chelseabender.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-melkasapi.git ./01-hello-world-melkasapi.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-aditithakkar17.git ./02-gc-percent-aditithakkar17.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-Mathewseltzer.git ./01-hello-world-Mathewseltzer.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-luckenbd.git ./01-hello-world-luckenbd.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-maria-perica.git ./01-hello-world-maria-perica.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-tmwynne.git ./01-hello-world-tmwynne.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-zhivkoplias.git ./01-hello-world-zhivkoplias.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-shlosman.git ./02-gc-percent-shlosman.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-beyfea.git ./01-hello-world-beyfea.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-marskar.git ./01-hello-world-marskar.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-gmahesh44.git ./01-hello-world-gmahesh44.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-chakraborty-r-arup.git ./01-hello-world-chakraborty-r-arup.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-jimankang.git ./01-hello-world-jimankang.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-siyoung74.git ./02-gc-percent-siyoung74.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-wolfgern.git ./01-hello-world-wolfgern.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-rolinskira.git ./01-hello-world-rolinskira.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-shennonlu.git ./01-hello-world-shennonlu.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-earnestt1234.git ./01-hello-world-earnestt1234.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-tmwynne.git ./02-gc-percent-tmwynne.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-jakobgu.git ./01-hello-world-jakobgu.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-laurenkomer.git ./01-hello-world-laurenkomer.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-sherineeltoukhy.git ./01-hello-world-sherineeltoukhy.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-krstofur.git ./01-hello-world-krstofur.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-dross33.git ./01-hello-world-dross33.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-blu21.git ./02-gc-percent-blu21.git
/usr/bin/git submodule add https://github.com/faes-biof/10-final-project-jpmcelderry.git ./10-final-project-jpmcelderry.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-saadi12k.git ./01-hello-world-saadi12k.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-vkh16.git ./01-hello-world-vkh16.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-maggiesundby.git ./01-hello-world-maggiesundby.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-jpmcelderry.git ./01-hello-world-jpmcelderry.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-renbinyang.git ./01-hello-world-renbinyang.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-naisargmodi.git ./01-hello-world-naisargmodi.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-michaelrosenheck.git ./01-hello-world-michaelrosenheck.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-KatSchwartz.git ./01-hello-world-KatSchwartz.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-simplevero123.git ./01-hello-world-simplevero123.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-chelseabender.git ./02-gc-percent-chelseabender.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-fellm033.git ./01-hello-world-fellm033.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-jhm471.git ./02-gc-percent-jhm471.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-jhm471.git ./03-loop-example-jhm471.git
/usr/bin/git submodule add https://github.com/faes-biof/10-final-project-jhm471.git ./10-final-project-jhm471.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-jpmcelderry.git ./02-gc-percent-jpmcelderry.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-yangr3.git ./02-gc-percent-yangr3.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-siyoung74.git ./03-loop-example-siyoung74.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-melkasapi.git ./02-gc-percent-melkasapi.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-earnestt1234.git ./02-gc-percent-earnestt1234.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-R-Mayers.git ./02-gc-percent-R-Mayers.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-pickles0618.git ./02-gc-percent-pickles0618.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-Mathewseltzer.git ./02-gc-percent-Mathewseltzer.git
/usr/bin/git submodule add https://github.com/faes-biof/08-make-a-plot-tmwynne.git ./08-make-a-plot-tmwynne.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-krstofur.git ./02-gc-percent-krstofur.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-rolinskira.git ./02-gc-percent-rolinskira.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-chakraborty-r-arup.git ./02-gc-percent-chakraborty-r-arup.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-michaelrosenheck.git ./02-gc-percent-michaelrosenheck.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-fellm033.git ./02-gc-percent-fellm033.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-saadtassaduq786.git ./02-gc-percent-saadtassaduq786.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-wolfgern.git ./02-gc-percent-wolfgern.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-shoos001.git ./02-gc-percent-shoos001.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-ReichardKyle.git ./02-gc-percent-ReichardKyle.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-Haibingquan.git ./01-hello-world-Haibingquan.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-Haibingquan.git ./02-gc-percent-Haibingquan.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-laurenkomer.git ./02-gc-percent-laurenkomer.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-aksenovavy.git ./01-hello-world-aksenovavy.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-jakobgu.git ./02-gc-percent-jakobgu.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-maria-perica.git ./02-gc-percent-maria-perica.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-shennonlu.git ./02-gc-percent-shennonlu.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-dross33.git ./02-gc-percent-dross33.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-watkinsta.git ./02-gc-percent-watkinsta.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-sherineeltoukhy.git ./02-gc-percent-sherineeltoukhy.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-shoos001.git ./03-loop-example-shoos001.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-aksenovavy.git ./02-gc-percent-aksenovavy.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-dakotajacobs.git ./02-gc-percent-dakotajacobs.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-zhivkoplias.git ./02-gc-percent-zhivkoplias.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-jpmcelderry.git ./03-loop-example-jpmcelderry.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-jimankang.git ./02-gc-percent-jimankang.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-ccole1993.git ./02-gc-percent-ccole1993.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-vkh16.git ./02-gc-percent-vkh16.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-saadi12k.git ./02-gc-percent-saadi12k.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-yangr3.git ./01-hello-world-yangr3.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-naisargmodi.git ./02-gc-percent-naisargmodi.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-ccole1993.git ./03-loop-example-ccole1993.git
/usr/bin/git submodule add https://github.com/faes-biof/04-conditionals-example-ccole1993.git ./04-conditionals-example-ccole1993.git
/usr/bin/git submodule add https://github.com/faes-biof/05-cubed-program-ccole1993.git ./05-cubed-program-ccole1993.git
/usr/bin/git submodule add https://github.com/faes-biof/06-numpy-problem-set-ccole1993.git ./06-numpy-problem-set-ccole1993.git
/usr/bin/git submodule add https://github.com/faes-biof/07-pandas-problem-set-ccole1993.git ./07-pandas-problem-set-ccole1993.git
/usr/bin/git submodule add https://github.com/faes-biof/08-make-a-plot-ccole1993.git ./08-make-a-plot-ccole1993.git
/usr/bin/git submodule add https://github.com/faes-biof/09-machine-learning-example-ccole1993.git ./09-machine-learning-example-ccole1993.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-jairafv.git ./01-hello-world-jairafv.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-wolfgern.git ./03-loop-example-wolfgern.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-jairafv.git ./02-gc-percent-jairafv.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-rolinskira.git ./03-loop-example-rolinskira.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-rahmanmm2.git ./02-gc-percent-rahmanmm2.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-KatSchwartz.git ./02-gc-percent-KatSchwartz.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-blu21.git ./03-loop-example-blu21.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-tejpalgill.git ./02-gc-percent-tejpalgill.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-marskar.git ./02-gc-percent-marskar.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-simplevero123.git ./02-gc-percent-simplevero123.git
/usr/bin/git submodule add https://github.com/faes-biof/02-gc-percent-beyfea.git ./02-gc-percent-beyfea.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-jimankang.git ./03-loop-example-jimankang.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-jakobgu.git ./03-loop-example-jakobgu.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-ksheard.git ./03-loop-example-ksheard.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-dross33.git ./03-loop-example-dross33.git
/usr/bin/git submodule add https://github.com/faes-biof/04-conditionals-example-jakobgu.git ./04-conditionals-example-jakobgu.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-pickles0618.git ./03-loop-example-pickles0618.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-shlosman.git ./03-loop-example-shlosman.git
/usr/bin/git submodule add https://github.com/faes-biof/04-conditionals-example-jimankang.git ./04-conditionals-example-jimankang.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-watkinsta.git ./03-loop-example-watkinsta.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-drewhonson.git ./03-loop-example-drewhonson.git
/usr/bin/git submodule add https://github.com/faes-biof/04-conditionals-example-siyoung74.git ./04-conditionals-example-siyoung74.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-R-Mayers.git ./03-loop-example-R-Mayers.git
/usr/bin/git submodule add https://github.com/faes-biof/05-cubed-program-tmwynne.git ./05-cubed-program-tmwynne.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-tmwynne.git ./03-loop-example-tmwynne.git
/usr/bin/git submodule add https://github.com/faes-biof/04-conditionals-example-tmwynne.git ./04-conditionals-example-tmwynne.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-ReichardKyle.git ./03-loop-example-ReichardKyle.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-gmahesh44.git ./03-loop-example-gmahesh44.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-maria-perica.git ./03-loop-example-maria-perica.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-dakotajacobs.git ./03-loop-example-dakotajacobs.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-sherineeltoukhy.git ./03-loop-example-sherineeltoukhy.git
/usr/bin/git submodule add https://github.com/faes-biof/04-conditionals-example-sherineeltoukhy.git ./04-conditionals-example-sherineeltoukhy.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-chelseabender.git ./03-loop-example-chelseabender.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-vkh16.git ./03-loop-example-vkh16.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-saadi12k.git ./03-loop-example-saadi12k.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-beyfea.git ./03-loop-example-beyfea.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-simplevero123.git ./03-loop-example-simplevero123.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-zhivkoplias.git ./03-loop-example-zhivkoplias.git
/usr/bin/git submodule add https://github.com/faes-biof/05-cubed-program-jakobgu.git ./05-cubed-program-jakobgu.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-shennonlu.git ./03-loop-example-shennonlu.git
/usr/bin/git submodule add https://github.com/faes-biof/04-conditionals-example-shennonlu.git ./04-conditionals-example-shennonlu.git
/usr/bin/git submodule add https://github.com/faes-biof/06-numpy-problem-set-jimankang.git ./06-numpy-problem-set-jimankang.git
/usr/bin/git submodule add https://github.com/faes-biof/04-conditionals-example-blu21.git ./04-conditionals-example-blu21.git
/usr/bin/git submodule add https://github.com/faes-biof/04-conditionals-example-rolinskira.git ./04-conditionals-example-rolinskira.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-aksenovavy.git ./03-loop-example-aksenovavy.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-earnestt1234.git ./03-loop-example-earnestt1234.git
/usr/bin/git submodule add https://github.com/faes-biof/04-conditionals-example-drewhonson.git ./04-conditionals-example-drewhonson.git
/usr/bin/git submodule add https://github.com/faes-biof/04-conditionals-example-chelseabender.git ./04-conditionals-example-chelseabender.git
/usr/bin/git submodule add https://github.com/faes-biof/05-cubed-program-drewhonson.git ./05-cubed-program-drewhonson.git
/usr/bin/git submodule add https://github.com/faes-biof/04-conditionals-example-gmahesh44.git ./04-conditionals-example-gmahesh44.git
/usr/bin/git submodule add https://github.com/faes-biof/06-numpy-problem-set-drewhonson.git ./06-numpy-problem-set-drewhonson.git
/usr/bin/git submodule add https://github.com/faes-biof/04-conditionals-example-pickles0618.git ./04-conditionals-example-pickles0618.git
/usr/bin/git submodule add https://github.com/faes-biof/04-conditionals-example-earnestt1234.git ./04-conditionals-example-earnestt1234.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-fellm033.git ./03-loop-example-fellm033.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-krstofur.git ./03-loop-example-krstofur.git
/usr/bin/git submodule add https://github.com/faes-biof/04-conditionals-example-fellm033.git ./04-conditionals-example-fellm033.git
/usr/bin/git submodule add https://github.com/faes-biof/06-numpy-problem-set-dross33.git ./06-numpy-problem-set-dross33.git
/usr/bin/git submodule add https://github.com/faes-biof/05-cubed-program-fellm033.git ./05-cubed-program-fellm033.git
/usr/bin/git submodule add https://github.com/faes-biof/04-conditionals-example-wolfgern.git ./04-conditionals-example-wolfgern.git
/usr/bin/git submodule add https://github.com/faes-biof/05-cubed-program-wolfgern.git ./05-cubed-program-wolfgern.git
/usr/bin/git submodule add https://github.com/faes-biof/05-cubed-program-blu21.git ./05-cubed-program-blu21.git
/usr/bin/git submodule add https://github.com/faes-biof/06-numpy-problem-set-fellm033.git ./06-numpy-problem-set-fellm033.git
/usr/bin/git submodule add https://github.com/faes-biof/07-pandas-problem-set-fellm033.git ./07-pandas-problem-set-fellm033.git
/usr/bin/git submodule add https://github.com/faes-biof/05-cubed-program-jhm471.git ./05-cubed-program-jhm471.git
/usr/bin/git submodule add https://github.com/faes-biof/06-numpy-problem-set-earnestt1234.git ./06-numpy-problem-set-earnestt1234.git
/usr/bin/git submodule add https://github.com/faes-biof/04-conditionals-example-jhm471.git ./04-conditionals-example-jhm471.git
/usr/bin/git submodule add https://github.com/faes-biof/06-numpy-problem-set-jhm471.git ./06-numpy-problem-set-jhm471.git
/usr/bin/git submodule add https://github.com/faes-biof/07-pandas-problem-set-jhm471.git ./07-pandas-problem-set-jhm471.git
/usr/bin/git submodule add https://github.com/faes-biof/09-machine-learning-example-jhm471.git ./09-machine-learning-example-jhm471.git
/usr/bin/git submodule add https://github.com/faes-biof/05-cubed-program-pickles0618.git ./05-cubed-program-pickles0618.git
/usr/bin/git submodule add https://github.com/faes-biof/06-numpy-problem-set-pickles0618.git ./06-numpy-problem-set-pickles0618.git
/usr/bin/git submodule add https://github.com/faes-biof/04-conditionals-example-shoos001.git ./04-conditionals-example-shoos001.git
/usr/bin/git submodule add https://github.com/faes-biof/04-conditionals-example-jpmcelderry.git ./04-conditionals-example-jpmcelderry.git
/usr/bin/git submodule add https://github.com/faes-biof/05-cubed-program-jpmcelderry.git ./05-cubed-program-jpmcelderry.git
/usr/bin/git submodule add https://github.com/faes-biof/08-make-a-plot-jpmcelderry.git ./08-make-a-plot-jpmcelderry.git
/usr/bin/git submodule add https://github.com/faes-biof/07-pandas-problem-set-drewhonson.git ./07-pandas-problem-set-drewhonson.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-laurenkomer.git ./03-loop-example-laurenkomer.git
/usr/bin/git submodule add https://github.com/faes-biof/04-conditionals-example-laurenkomer.git ./04-conditionals-example-laurenkomer.git
/usr/bin/git submodule add https://github.com/faes-biof/04-conditionals-example-R-Mayers.git ./04-conditionals-example-R-Mayers.git
/usr/bin/git submodule add https://github.com/faes-biof/10-final-project-sherineeltoukhy.git ./10-final-project-sherineeltoukhy.git
/usr/bin/git submodule add https://github.com/faes-biof/05-cubed-program-sherineeltoukhy.git ./05-cubed-program-sherineeltoukhy.git
/usr/bin/git submodule add https://github.com/faes-biof/06-numpy-problem-set-sherineeltoukhy.git ./06-numpy-problem-set-sherineeltoukhy.git
/usr/bin/git submodule add https://github.com/faes-biof/07-pandas-problem-set-sherineeltoukhy.git ./07-pandas-problem-set-sherineeltoukhy.git
/usr/bin/git submodule add https://github.com/faes-biof/08-make-a-plot-sherineeltoukhy.git ./08-make-a-plot-sherineeltoukhy.git
/usr/bin/git submodule add https://github.com/faes-biof/09-machine-learning-example-sherineeltoukhy.git ./09-machine-learning-example-sherineeltoukhy.git
/usr/bin/git submodule add https://github.com/faes-biof/10-final-project-saadi12k.git ./10-final-project-saadi12k.git
/usr/bin/git submodule add https://github.com/faes-biof/04-conditionals-example-saadi12k.git ./04-conditionals-example-saadi12k.git
/usr/bin/git submodule add https://github.com/faes-biof/05-cubed-program-saadi12k.git ./05-cubed-program-saadi12k.git
/usr/bin/git submodule add https://github.com/faes-biof/06-numpy-problem-set-saadi12k.git ./06-numpy-problem-set-saadi12k.git
/usr/bin/git submodule add https://github.com/faes-biof/07-pandas-problem-set-saadi12k.git ./07-pandas-problem-set-saadi12k.git
/usr/bin/git submodule add https://github.com/faes-biof/08-make-a-plot-saadi12k.git ./08-make-a-plot-saadi12k.git
/usr/bin/git submodule add https://github.com/faes-biof/09-machine-learning-example-saadi12k.git ./09-machine-learning-example-saadi12k.git
/usr/bin/git submodule add https://github.com/faes-biof/04-conditionals-example-watkinsta.git ./04-conditionals-example-watkinsta.git
/usr/bin/git submodule add https://github.com/faes-biof/10-final-project-ksheard.git ./10-final-project-ksheard.git
/usr/bin/git submodule add https://github.com/faes-biof/10-final-project-beyfea.git ./10-final-project-beyfea.git
/usr/bin/git submodule add https://github.com/faes-biof/10-final-project-blu21.git ./10-final-project-blu21.git
/usr/bin/git submodule add https://github.com/faes-biof/10-final-project-laurenkomer.git ./10-final-project-laurenkomer.git
/usr/bin/git submodule add https://github.com/faes-biof/04-conditionals-example-zhivkoplias.git ./04-conditionals-example-zhivkoplias.git
/usr/bin/git submodule add https://github.com/faes-biof/10-final-project-R-Mayers.git ./10-final-project-R-Mayers.git
/usr/bin/git submodule add https://github.com/faes-biof/10-final-project-rolinskira.git ./10-final-project-rolinskira.git
/usr/bin/git submodule add https://github.com/faes-biof/10-final-project-earnestt1234.git ./10-final-project-earnestt1234.git
/usr/bin/git submodule add https://github.com/faes-biof/10-final-project-watkinsta.git ./10-final-project-watkinsta.git
/usr/bin/git submodule add https://github.com/faes-biof/10-final-project-shlosman.git ./10-final-project-shlosman.git
/usr/bin/git submodule add https://github.com/faes-biof/10-final-project-melkasapi.git ./10-final-project-melkasapi.git
/usr/bin/git submodule add https://github.com/faes-biof/04-conditionals-example-ksheard.git ./04-conditionals-example-ksheard.git
/usr/bin/git submodule add https://github.com/faes-biof/10-final-project-shoos001.git ./10-final-project-shoos001.git
/usr/bin/git submodule add https://github.com/faes-biof/05-cubed-program-shoos001.git ./05-cubed-program-shoos001.git
/usr/bin/git submodule add https://github.com/faes-biof/04-conditionals-example-shlosman.git ./04-conditionals-example-shlosman.git
/usr/bin/git submodule add https://github.com/faes-biof/10-final-project-shennonlu.git ./10-final-project-shennonlu.git
/usr/bin/git submodule add https://github.com/faes-biof/04-conditionals-example-dakotajacobs.git ./04-conditionals-example-dakotajacobs.git
/usr/bin/git submodule add https://github.com/faes-biof/10-final-project-aksenovavy.git ./10-final-project-aksenovavy.git
/usr/bin/git submodule add https://github.com/faes-biof/10-final-project-chelseabender.git ./10-final-project-chelseabender.git
/usr/bin/git submodule add https://github.com/faes-biof/10-final-project-tmwynne.git ./10-final-project-tmwynne.git
/usr/bin/git submodule add https://github.com/faes-biof/10-final-project-wolfgern.git ./10-final-project-wolfgern.git
/usr/bin/git submodule add https://github.com/faes-biof/10-final-project-dakotajacobs.git ./10-final-project-dakotajacobs.git
/usr/bin/git submodule add https://github.com/faes-biof/01-hello-world-huzefakhan.git ./01-hello-world-huzefakhan.git
/usr/bin/git submodule add https://github.com/faes-biof/10-final-project-naisargmodi.git ./10-final-project-naisargmodi.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-naisargmodi.git ./03-loop-example-naisargmodi.git
/usr/bin/git submodule add https://github.com/faes-biof/04-conditionals-example-naisargmodi.git ./04-conditionals-example-naisargmodi.git
/usr/bin/git submodule add https://github.com/faes-biof/04-conditionals-example-ReichardKyle.git ./04-conditionals-example-ReichardKyle.git
/usr/bin/git submodule add https://github.com/faes-biof/04-conditionals-example-vkh16.git ./04-conditionals-example-vkh16.git
/usr/bin/git submodule add https://github.com/faes-biof/10-final-project-vkh16.git ./10-final-project-vkh16.git
/usr/bin/git submodule add https://github.com/faes-biof/03-loop-example-melkasapi.git ./03-loop-example-melkasapi.git
/usr/bin/git submodule add https://github.com/faes-biof/04-conditionals-example-melkasapi.git ./04-conditionals-example-melkasapi.git
